# Generated by Django 5.1.2 on 2024-11-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_subject_notebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='color',
            field=models.CharField(default='white', max_length=32, null=True),
        ),
    ]
