# Generated by Django 5.1.2 on 2024-11-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_page_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcardsubject',
            old_name='flash_card',
            new_name='flashcard',
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='subjects',
            field=models.ManyToManyField(through='client.FlashcardSubject', to='client.subject'),
        ),
    ]
