# Generated by Django 5.1.2 on 2024-11-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_rename_flash_card_flashcardsubject_flashcard_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pomodoro',
            old_name='focus_sessions_before_long_break',
            new_name='focus_sessions',
        ),
    ]
