# Generated by Django 5.1.2 on 2024-11-17 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_rename_long_break_time_pomodoro_rest_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='subjects',
            field=models.ManyToManyField(null=True, through='client.FlashcardSubject', to='client.subject'),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='break_time',
            field=models.DurationField(default=datetime.timedelta(seconds=60)),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='focus_sessions',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='focus_time',
            field=models.DurationField(default=datetime.timedelta(seconds=60)),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='rest_time',
            field=models.DurationField(default=datetime.timedelta(seconds=60)),
        ),
    ]
