# Generated by Django 5.1.2 on 2024-11-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_flashcard_subjects_alter_pomodoro_break_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='subjects',
            field=models.ManyToManyField(blank=True, through='client.FlashcardSubject', to='client.subject'),
        ),
    ]
