# Generated by Django 5.0.6 on 2024-08-08 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('color', models.CharField(default='white', max_length=32)),
                ('content', models.TextField(default='<p></p>')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notebook', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_time', models.DurationField(default='00:40:00')),
                ('break_time', models.DurationField(default='00:10:00')),
                ('rest_time', models.DurationField(default='00:30:00')),
                ('focus_sessions_until_rest', models.PositiveSmallIntegerField(default=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='New subject', max_length=32)),
                ('color', models.CharField(default='white', max_length=32)),
                ('last_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_subject', to='main_pages.page')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='main_pages.notebook')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='main_pages.subject'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='last_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_subject', to='main_pages.subject'),
        ),
        migrations.CreateModel(
            name='FlashCardSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flash_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_subject', to='main_pages.flashcard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_subject', to='main_pages.subject')),
            ],
        ),
        migrations.AddField(
            model_name='flashcard',
            name='subjects',
            field=models.ManyToManyField(through='main_pages.FlashCardSubject', to='main_pages.subject'),
        ),
    ]
