# Generated by Django 5.0.6 on 2024-08-08 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodoro',
            name='break_time',
            field=models.DurationField(default=datetime.timedelta(seconds=600)),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='focus_time',
            field=models.DurationField(default=datetime.timedelta(seconds=2400)),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='rest_time',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
