# Generated by Django 5.0.6 on 2024-08-11 17:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0002_alter_pomodoro_break_time_alter_pomodoro_focus_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardsubject',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
