# Generated by Django 5.0.6 on 2024-08-11 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0003_alter_flashcardsubject_id_alter_notebook_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='notebook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='main_pages.notebook'),
        ),
    ]
