# Generated by Django 5.0.6 on 2024-08-13 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0004_alter_subject_notebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='main_pages.notebook'),
        ),
    ]
